future: true
permalink: /:title/
url: http://www.noodler.xyz
name: 面条丶
author: Ju
qq:
email: amistsss@163.com
duoshuo: Juzzzzzz
beian:
cnzz:
weibo: Juzzzzzz
github: Juzzzzzz
paginate: 20
highlighter: rouge
truncate: true
about: "面条丶"
